name: Deploy

on:
  pull_request:
    types: [ closed ]

  workflow_dispatch:
    inputs:
      dispatch:
        default: true

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event.inputs.dispatch == true
    runs-on: ubuntu-latest
    env:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: |
          git submodule update --init
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Generate guides files
        run: rake guides:generate:html
      - name: Git setup
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git stash --include-untracked
          git checkout --track origin/site
      - name: Commit site changes
        run: |
          rm site/javascripts/lunr-documents.js
          rm site/javascripts/lunr-index.js
          git stash apply
          cp $(find output/pt-BR -name "*.html") site
          git add site/
          git commit -m "Build from commit ${GITHUB_SHA}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          branch: 'site'
      - name: Comment on merged pull request
        run: |
          curl --silent --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
          --header 'Accept: application/vnd.github.squirrel-girl-preview' \
          --header 'Authorization: token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "body": "Já está disponível no Guia Rails :tada: :rocket:"
          }' > /dev/null
      - name: Add label on merged pull request
        run: |
          curl --silent --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
          --header 'Accept: application/vnd.github.squirrel-girl-preview' \
          --header 'Authorization: token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "labels": [":rocket:"]
          }' > /dev/null
